apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: nginx-pod

spec:
  selector:
    matchLabels:
      app: cw-pod

  template:
    metadata:
      labels:
        app: cw-pod

    spec:
      containers:
      - name: nginx
        image: amazon/cloudwatch-agent
        ports:
       ports:
          - containerPort: 80
            name: cw-port
